name: Builds documentation and checks coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docs-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Upload the documentation artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: documentation-artifact
          path: target/apidocs/
      - name: Upload the coverage artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: coverage-artifact
          path: target/site/jacoco/
